export const ADD_QUESTIONNAIRE = "ADD_QUESTIONNAIRE";
export const EDIT_QUESTIONNAIRE = "EDIT_QUESTIONNAIRE";
export const REMOVE_QUESTIONNAIRE = "REMOVE_QUESTIONNAIRE";
export const EDIT_TITLE = "EDIT_TITLE";
export const CONFIRM_TITLE = "CONFIRM_TITLE";
export const ADD_QUESTION = "ADD_QUESTION";
export const CHOOSE_TYPE = "CHOOSE_TYPE";